name: pediatria_app_movil
description: Una nueva aplicaci贸n Flutter.

# Versi贸n de la aplicaci贸n
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Archivos de assets para la aplicaci贸n.
  assets:
    - lib/assets/images/LogoHospital.png