name: pediatria_app_movil
description: Una nueva aplicación Flutter.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: 1.2.2
  fl_chart: 0.69.2
  firebase_core: ^3.1.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.0.2  # Asegúrate de tener la versión más reciente
  intl: ^0.20.1
  flutter_web_auth_2: ^4.1.0
  google_sign_in: ^6.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Archivos de assets para la aplicación.
  assets:
    - lib/assets/images/